[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12"
tonic = "0.11"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tonic-build = "0.11"
protobuf-src = "1.1"
